version: '2'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    command: npm run dev
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    links:
      - postgres

  worker:
    build: .
    command: npm run worker
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    links:
      - postgres

  postgres:
    image: postgres

volumes:
  node_modules:
