application: uq-newwwness
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
# site root
- url: /
  static_files: build/index.html
  upload: build/index.html
  mime_type: text/html
  expiration: "15m"
  # login: admin

- url: /(.*\.svg)
  static_files: build/\1
  upload: build/(.*\.svg)
  mime_type: image/svg+xml

- url: /(.*\.css)
  mime_type: text/css
  static_files: build/\1
  upload: build/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: build/\1
  upload: build/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: build/\1
  upload: build/(.*\.json)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|woff|ttf|eot))
  static_files: build/\1
  upload: build/(.*\.(svg|bmp|gif|ico|jpeg|jpg|png|woff|ttf|eot))

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^source$
  - ^node_modules$
  - ^bower_components$