application: uq-newwwness
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /n/
  static_files: public/n/index.html
  upload: public/n/index.html

- url: /
  static_dir: public

